# Generated by Django 3.0.7 on 2020-06-21 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=245, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('driver_pic', models.ImageField(upload_to='driver_images')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QuickEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name is required', max_length=50)),
                ('email', models.EmailField(help_text='Email is required', max_length=245)),
                ('phone', models.CharField(help_text='Phone is required', max_length=20)),
                ('message', models.TextField(help_text='What can we help you with?')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_name', models.CharField(max_length=60)),
                ('students_address', models.CharField(max_length=200)),
                ('students_phone', models.CharField(max_length=50)),
                ('primary_contact', models.CharField(max_length=200)),
                ('primary_phone', models.CharField(max_length=50)),
                ('secondary_contact', models.CharField(max_length=200)),
                ('secondary_phone', models.CharField(max_length=50)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=50)),
                ('relationship_to_student', models.CharField(help_text='Relationship to student', max_length=100)),
                ('medical_plan', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Does student have a medical plan?', max_length=3)),
                ('medical_reason', models.CharField(blank=True, default='None', max_length=100)),
                ('destination', models.CharField(max_length=50)),
                ('destination_address', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('monday_arrival_and_departure_times', models.CharField(help_text='Eg.8:00:00 am ,12:30:00 pm', max_length=50)),
                ('tuesday_arrival_and_departure_times', models.CharField(help_text='Eg.8:00:00 am ,12:30:00 pm', max_length=50)),
                ('wednesday_arrival_and_departure_times', models.CharField(help_text='Eg.8:00:00 am ,12:30:00 pm', max_length=50)),
                ('thursday_arrival_and_departure_times', models.CharField(help_text='Eg.8:00:00 am ,12:30:00 pm', max_length=50)),
                ('friday_arrival_and_departure_times', models.CharField(help_text='Eg.8:00:00 am ,12:30:00 pm', max_length=50)),
                ('school_contact', models.CharField(max_length=100)),
                ('school_phone', models.CharField(max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=250)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
